# Generated by Django 3.1.2 on 2020-10-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiobook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='file',
            new_name='file_field',
        ),
    ]
